name: Build Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check for build files
      run: |
        echo "Checking for build configuration files..."
        if [ -f "Makefile" ]; then
          echo "Found Makefile"
          BUILD_SYSTEM="make"
        elif [ -f "CMakeLists.txt" ]; then
          echo "Found CMakeLists.txt"
          BUILD_SYSTEM="cmake"
        elif [ -f "package.json" ]; then
          echo "Found package.json"
          BUILD_SYSTEM="npm"
        elif [ -f "platformio.ini" ]; then
          echo "Found platformio.ini"
          BUILD_SYSTEM="platformio"
        elif [ -f "src/" ] && [ "$(find src -name '*.c' -o -name '*.cpp' -o -name '*.ino' | wc -l)" -gt 0 ]; then
          echo "Found C/C++ source files"
          BUILD_SYSTEM="gcc"
        else
          echo "No recognized build system found"
          BUILD_SYSTEM="none"
        fi
        echo "BUILD_SYSTEM=$BUILD_SYSTEM" >> $GITHUB_ENV
        
    - name: Setup build environment
      run: |
        case $BUILD_SYSTEM in
          "make"|"gcc")
            sudo apt-get update
            sudo apt-get install -y build-essential
            ;;
          "cmake")
            sudo apt-get update
            sudo apt-get install -y build-essential cmake
            ;;
          "npm")
            node --version
            npm --version
            ;;
          "platformio")
            pip install platformio
            ;;
          *)
            echo "No specific build tools needed"
            ;;
        esac
        
    - name: Build project
      run: |
        case $BUILD_SYSTEM in
          "make")
            echo "Building with Make..."
            make
            ;;
          "cmake")
            echo "Building with CMake..."
            mkdir -p build
            cd build
            cmake ..
            make
            ;;
          "npm")
            echo "Building with npm..."
            npm install
            npm run build
            ;;
          "platformio")
            echo "Building with PlatformIO..."
            pio run
            ;;
          "gcc")
            echo "Building with GCC..."
            gcc -o main src/*.c 2>/dev/null || gcc -o main *.c 2>/dev/null || echo "No C files to compile"
            ;;
          *)
            echo "⚠️ No build system detected. Please add build configuration files."
            echo "For embedded projects, consider adding:"
            echo "- Makefile for Make builds"
            echo "- CMakeLists.txt for CMake builds"
            echo "- platformio.ini for PlatformIO builds"
            exit 1
            ;;
        esac
        
    - name: Build status
      run: |
        if [ $? -eq 0 ]; then
          echo "✅ Build successful!"
        else
          echo "❌ Build failed!"
          exit 1
        fi
