name: PlatformIO CI Build

on:
  push:
    branches: [main, SensorUnit_dev]
  pull_request:
    branches: [main, SensorUnit_dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Copy arduino_secrets_template.h to arduino_secrets.h
        run: cp SensorUnit/src/arduino_secrets_template.h SensorUnit/src/arduino_secrets.h

      - name: Build SensorUnit firmware
        run: |
          platformio run --project-dir SensorUnit

      - name: Run cppcheck static analysis
        run: |
          platformio check --project-dir SensorUnit || true
